sudo: true
language: android
dist: trusty
install: true
jdk:
- oraclejdk8
branches:
  only:
  - master
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew
script: 
  - ./gradlew -S clean build 
